"""Add email to User model

Revision ID: 1114ec2510d7
Revises: r20251115a
Create Date: 2025-11-19 20:19:51.648376

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1114ec2510d7'
down_revision = 'r20251115a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leave_table')
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_constraint('fk_document_leave', type_='foreignkey')
        batch_op.create_foreign_key(None, 'leave', ['leave_id'], ['id'])

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_constraint('fk_notification_user', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('email')

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_notification_user', 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_document_leave', 'leave_table', ['leave_id'], ['id'], ondelete='CASCADE')

    op.create_table('leave_table',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('start_date', sa.DATE(), nullable=False),
    sa.Column('end_date', sa.DATE(), nullable=False),
    sa.Column('duration_months', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('duration_days', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('leave_type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('reason', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=20), server_default=sa.text("'Pending'"), nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('employee_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('employee_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('designation', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_leave_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
