"""add_employee_name_to_leave

Revision ID: 9bf499a6d2c5
Revises: 
Create Date: 2025-05-05 15:17:56.116607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bf499a6d2c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_name', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave', schema=None) as batch_op:
        batch_op.drop_column('employee_name')

    # ### end Alembic commands ###
