"""add_employee_name_to_leave_model

Revision ID: e031abb3bee2
Revises: 9bf499a6d2c5
Create Date: 2025-05-08 09:59:31.112426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e031abb3bee2'
down_revision = '9bf499a6d2c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave', schema=None) as batch_op:
        batch_op.drop_column('employee_name')

    # ### end Alembic commands ###
